CREATE TABLE brand (
  name VARCHAR(50) PRIMARY KEY
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE model (
  id INT(3) AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  YEAR INT(4) NOT NULL,
  brand_name VARCHAR(50),
  FOREIGN KEY (brand_name) REFERENCES brand (name) ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE vehicle (
  license_plate VARCHAR(10) PRIMARY KEY,
  avg_consumption DOUBLE(3,1) NOT NULL,
  fuel VARCHAR(10) NOT NULL,
  brand_name VARCHAR(50),
  model_id INT(3),
  FOREIGN KEY (brand_name) REFERENCES brand (name) ON UPDATE RESTRICT,
  FOREIGN KEY (model_id) REFERENCES model (id) ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
